export const services = [
  {
    slug: "algemene-elektriciteit",
    title: "Algemene elektriciteit",
    shortDescription: "Volledige elektrische installaties voor nieuwbouw en renovatie.",
    description: "Van de eerste bekabeling tot de laatste afwerking. Elektro De Vlieger verzorgt uw volledige elektrische installatie volgens de laatste normen en regelgeving. Of het nu gaat om een nieuwbouwproject of een grondige renovatie, elk project wordt vakkundig aangepakt.",
    details: [
      "Volledige elektrische installaties nieuwbouw",
      "Renovatie en vernieuwing bestaande installaties",
      "Verdeelkasten en zekeringkasten",
      "Bekabeling en bedrading",
      "Stopcontacten, schakelaars en verlichting",
      "Elektrische keuringen en conformiteitsattesten",
    ],
    image: "/images/fb-elektra-nieuwbouw.jpg",
  },
  {
    slug: "zonnepanelen",
    title: "Zonnepanelen",
    shortDescription: "Installatie van zonnepanelen op maat voor particulieren en bedrijven.",
    description: "Profiteer van groene energie en verlaag uw energiefactuur structureel. Elektro De Vlieger installeert zonnepanelen op maat, zowel op schuine als platte daken. We begeleiden u van advies tot installatie en zorgen voor alle administratie.",
    details: [
      "Installatie op schuine en platte daken",
      "Particuliere en commerciele projecten",
      "Advies over optimale capaciteit",
      "Administratie premies en certificaten",
      "Monitoring en onderhoud",
      "Combinatie met thuisbatterij en laadpaal",
    ],
    image: "/images/fb-zonnepanelen-dak.webp",
  },
  {
    slug: "thuisbatterij",
    title: "Thuisbatterij",
    shortDescription: "Sla uw zonne-energie op en gebruik ze wanneer u wilt.",
    description: "Met een thuisbatterij slaat u overtollige zonne-energie op voor later gebruik. Zo bent u minder afhankelijk van het net en maximaliseert u het rendement van uw zonnepanelen. Elektro De Vlieger adviseert en installeert de juiste batterij voor uw situatie.",
    details: [
      "Advies over het juiste type en capaciteit",
      "Installatie en aansluiting op uw installatie",
      "Integratie met bestaande zonnepanelen",
      "Slimme energieopslag en -beheer",
      "Noodstroomfunctie mogelijk",
      "Monitoring via app",
    ],
    image: "/images/fb-thuisbatterij.webp",
  },
  {
    slug: "laadpalen",
    title: "Laadpalen",
    shortDescription: "Laadpaal voor thuis of op het werk, klaar voor de toekomst.",
    description: "De overstap naar elektrisch rijden begint met een goede laadoplossing. Elektro De Vlieger installeert laadpalen voor thuis, op kantoor of op bedrijfsterreinen. Slim laden, snel geinstalleerd en klaar voor de toekomst.",
    details: [
      "Thuisladers en bedrijfslaadpalen",
      "Slim laden (load balancing)",
      "Integratie met zonnepanelen",
      "Geschikt voor alle automerken",
      "Advies over de juiste capaciteit",
      "Installatie conform alle regelgeving",
    ],
    image: "/images/fb-laadpaal.jpg",
  },
  {
    slug: "domotica",
    title: "Domotica",
    shortDescription: "Slimme verlichting, verwarming en beveiliging vanuit uw smartphone.",
    description: "Maak van uw woning een smart home. Elektro De Vlieger integreert slimme systemen voor verlichting, verwarming, zonwering en beveiliging. Bedien alles vanuit uw smartphone, overal ter wereld. Comfort, energiebesparing en veiligheid in een.",
    details: [
      "Slimme verlichting en dimming",
      "Automatische zonwering",
      "Intelligente verwarming en klimaatregeling",
      "Beveiligingssystemen en camera's",
      "Bediening via smartphone of tablet",
      "Integratie met bestaande systemen",
    ],
    image: "/images/fb-verlichting-woonkamer.jpg",
  },
  {
    slug: "ventilatie",
    title: "Ventilatie",
    shortDescription: "Ventilatiesystemen voor een gezond binnenklimaat.",
    description: "Een goed ventilatiesysteem is essentieel voor een gezond binnenklimaat. Elektro De Vlieger plaatst ventilatiesystemen type C en D, professioneel afgestemd op uw woning. Frisse lucht, minder vocht en een lager energieverbruik.",
    details: [
      "Ventilatiesysteem type C en D",
      "Warmteterugwinning (WTW)",
      "Vraaggestuurde ventilatie",
      "CO2- en vochtgestuurde roosters",
      "Onderhoud en filtervervanging",
      "Advies bij nieuwbouw en renovatie",
    ],
    image: "/images/fb-elektra-nieuwbouw.jpg",
  },
];

export const reviews = [
  {
    text: "Mijn renovatieproject van A tot Z voorzien van bekabeling, kast, ventilatiesysteem, domotica, zonnepanelen, ... steeds bereikbaar en komt zijn afspraken altijd na. Bedankt Robbe!!",
    author: "Kono de Zutter",
    role: "Google Review",
    rating: 5,
  },
  {
    text: "Kwaliteit - betrouwbaarheid - netheid - vriendelijkheid en gedienstigheid zijn de kernwoorden waarmee ik Robbe zou omschrijven. Een echte aanrader!",
    author: "Bart Broucke",
    role: "Google Review",
    rating: 5,
  },
];

export const projects = [
  { src: "/images/fb-verlichting-woonkamer.jpg", title: "Woonkamer - sfeerverlichting" },
  { src: "/images/fb-zonnepanelen-dak.webp", title: "Zonnepanelen - plat dak" },
  { src: "/images/fb-verlichting-keuken.jpg", title: "Keuken - moderne verlichting" },
  { src: "/images/fb-laadpaal.jpg", title: "Laadpaal - woning" },
  { src: "/images/fb-verlichting-woonkamer-bar.jpg", title: "Interieur - barverlichting" },
  { src: "/images/fb-thuisbatterij.webp", title: "Thuisbatterij - Huawei" },
  { src: "/images/fb-elektra-nieuwbouw.jpg", title: "Bekabeling - nieuwbouw" },
  { src: "/images/fb-verlichting-woonkamer.jpg", title: "Woonkamer - spots & haard" },
  { src: "/images/fb-zonnepanelen-plat-dak.jpg", title: "Zonnepanelen - bedrijfsdak" },
  { src: "/images/fb-verlichting-keuken.jpg", title: "Keuken - designverlichting" },
  { src: "/images/fb-zonnepanelen-schuin-dak.jpg", title: "Zonnepanelen - schuin dak" },
  { src: "/images/fb-omvormers-batterijen.webp", title: "Omvormers & batterijen" },
  { src: "/images/appartement-verlichting.jpeg", title: "Appartement - hanglampen" },
  { src: "/images/badkamer-led.jpeg", title: "Badkamer - LED spiegel" },
  { src: "/images/buitenverlichting-nacht.jpeg", title: "Buitenverlichting - gevel" },
  { src: "/images/zonnepanelen.jpeg", title: "Zonnepanelen - plat dak" },
];
